lib/micro_web/router.ex
defmodule MicroWeb.Router do
  use MicroWeb, :router
  import MicroWeb.Plugs

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_user
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_user
  end


  scope "/", MicroWeb do
    pipe_through :browser # Use the default browser stack
    get "/", PageController, :index

    # associate posts with users
    resources "/users", UserController do
      resources "/posts", PostController
    end

    post "/relationships", RelationshipController, :follow
    delete "/relationships", RelationshipController, :unfollow
    resources "/relationships", RelationshipController

    post "/sessions", SessionController, :login
    delete "/sessions", SessionController, :logout
  end

  scope "/api/v1", MicroWeb do
    pipe_through :api
    #get "/likes", LikeController, :show
    delete "/likes", LikeController, :delete
    post "/likes", LikeController, :create
    resources "/likes", LikeController, except: [:edit, :delete]

  end


  # Other scopes may use custom stacks.
  # scope "/api", MicroWeb do
  #   pipe_through :api
  # end
end

lib/micro/blog/post.ex
defmodule Micro.Blog.Post do
  use Ecto.Schema
  import Ecto.Changeset
  alias Micro.Blog.Post


  schema "posts" do
    field :body, :string
    field :title, :string
    belongs_to :user, Micro.Accounts.User
    has_many :likes, Micro.Blog.Like

    timestamps()
  end

  @doc false
  def changeset(%Post{} = post, attrs) do
    post
    |> cast(attrs, [:title, :body])
    |> validate_required([:title, :body])
  end

  def as_markdown(txt) do
    txt
    |> Earmark.as_html!()
    |> Phoenix.HTML.raw()
  end
end

lib/micro_web/controllers/post_controller.ex
defmodule MicroWeb.PostController do
  use MicroWeb, :controller

  alias Micro.Blog
  alias Micro.Blog.Post

  plug :assign_user
  plug :authorize_user when action in [:new, :create, :update, :edit, :delete]

  def index(conn, _params) do
    user = conn.assigns[:user]
    if user do
      posts = Enum.reverse(Blog.list_posts(user))
      render(conn, "index.html", posts: posts)
    else
      conn
      |> put_flash(:error, "Invalid user")
      |> redirect(to: user_path(conn, :index))
    end

  end

  def new(conn, _params) do
    changeset =
      conn.assigns[:user]
      |> Ecto.build_assoc(:posts)
      |> Blog.change_post()
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"post" => post_params}) do
    case Blog.create_post(conn.assigns[:user], post_params) do
      {:ok, post} ->
        # broadcast post to all follower channels
        Micro.Accounts.broadcast_post_to_followers(conn.assigns[:user].id, post)
        conn
        |> redirect(to: user_post_path(conn, :show, conn.assigns[:user], post))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  # used in posting via channels
  def create(%{"user_id" => user_id, "post" => post_params}) do
    user = Micro.Accounts.get_user!(user_id)
    case Blog.create_post(user, post_params) do
      {:ok, post} ->
        Micro.Accounts.broadcast_post_to_followers(user.id, post)
        {:ok, post}
      {:error, _changeset} ->
        {:error, %{reason: "Invalid attributes"}}
    end
  end

  def show(conn, %{"id" => id}) do
    post = Blog.get_post!(conn.assigns[:user], id)
    render(conn, "show.html", post: post)
  end

  def edit(conn, %{"id" => id}) do
    post = Blog.get_post!(conn.assigns[:user], id)
    changeset = Blog.change_post(post)
    render(conn, "edit.html", post: post, changeset: changeset)
  end

  def update(conn, %{"id" => id, "post" => post_params}) do
    post = Blog.get_post!(conn.assigns[:user], id)

    case Blog.update_post(post, post_params) do
      {:ok, post} ->
        conn
        |> redirect(to: user_post_path(conn, :show, conn.assigns[:user], post))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", post: post, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    user = conn.assigns[:user]
    post = Blog.get_post!(user, id)
    {:ok, _post} = Blog.delete_post(post)

    conn
    |> redirect(to: user_path(conn, :show, user))
  end

  defp assign_user(conn, _opts) do
    case conn.params do
      %{"user_id" => user_id} ->
        case Micro.Repo.get(Micro.Accounts.User, user_id) do
          nil -> invalid_user(conn) # this should never happen
          user -> assign(conn, :user, user)
        end
      _ -> invalid_user(conn)
    end
  end

  defp invalid_user(conn) do
    conn
    |> put_flash(:error, "Invalid user")
    |> redirect(to: page_path(conn, :index))
  end

  defp authorize_user(conn, _opts) do
    user = conn.assigns[:user]
    current_user = conn.assigns[:current_user]
    if current_user && current_user.id == user.id do
      conn
    else
      conn
      |> put_flash(:error, "Unauthorized access of posts")
      |> redirect(to: page_path(conn, :index))
    end
  end
end

lib/micro_web/views/post_view.ex
defmodule MicroWeb.PostView do
  use MicroWeb, :view
end

lib/micro_web/templates/post/edit.html.eex
<div class="col-md-12">
    <div class="row">
    <div class="col-md-6">
        <h1>edit post</h1>
    </div>
    <div class="col-md-6">
        <span class="float-right"><%= link "delete post",
         to: user_post_path(@conn, :delete, @user, @post), method: :delete, data: [confirm: "Are you sure?"],
         class: "btn btn-danger btn-xs", id: "delete-post" %></span>
    </div>
</div>

<%= render "form.html", Map.put(assigns, :action, user_post_path(@conn, :update, @user, @post)) %>

lib/micro_web/templates/post/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= text_input f, :title, class: "form-control", placeholder: "title" %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <%= textarea f, :body, class: "form-control", placeholder: "body" %>
    <%= error_tag f, :body %>
  </div>

  <div class="col-md-12 text-center form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/micro_web/templates/post/index.html.eex
<%= for post <- @posts do %>

        <div class="row mt-5">
            <div class="col-md-8 mx-auto">
                <div class="card bg-light">
                    <div class="card-header">
                        <a class="card-tag" href="<%= user_path(@conn, :show, @user)%>">
                            @<%= @user.handle %> </a>
                    </div>
                    <div class="card-body">
                        <a class="card-tag" href="<%= user_post_path(@conn, :show, @user, post) %>"><h5 class="text-center"><strong> <%= post.title %> </strong></h4></a>
                        <p><%= Micro.Blog.Post.as_markdown(post.body) %></p>
                    </div>
                </div>
            </div>
        </div>
<% end %>

lib/micro_web/templates/post/new.html.eex
<h2>New Post</h2>

<%= render "form.html", Map.put(assigns, :action, user_post_path(@conn, :create, @user)) %>

lib/micro_web/templates/post/show.html.eex
        <div class="col-md-12">
            <div class="row mb-2">
                <div class="col-md-8">
                    <a class="card-tag" href="<%= user_path(@conn, :show, @post.user) %>">
                    <span class="font-weight-bold h4 mr-4"> <%= @post.user.name %></span>
                    <span> @<%= @post.user.handle %> </span>
                    </a>
                </div>

            </div>
            </div>

            <div class="col-md-2">
                <%= if @current_user && @current_user.id == @post.user.id do %>
                    <%= link("edit", to: user_path(@conn, :edit, @post.user), class: "btn btn-sm btn-primary") %>
                <% else %>
                    <%= if @current_user && Micro.Accounts.get_relationship(@current_user.id, @post.user.id) do %>
                        <%= link("unfollow", to: relationship_path(@conn, :unfollow, current: @current_user, user: @post.user), method: :delete, class: "btn btn-sm btn-primary") %>
                    <% end %>
                    <%= if @current_user && !Micro.Accounts.get_relationship(@current_user.id, @post.user.id) do %>
                        <%= link("follow", to: relationship_path(@conn, :follow, current: @current_user, user: @post.user), method: :post, class: "btn btn-sm btn-primary") %>
                    <% end %>
                <% end %>
            </div>


<div class="col-md-8 m-auto">
    <h1 class="text-center"><%= @post.title %></h1>
</div>

<%= if @current_user && @current_user.id == @user.id do %>
<div class=col-md-12 m-auto">
    <span class="float-right"><%= link "edit post", to: user_post_path(@conn, :edit, @user, @post), class: "btn btn-primary btn-sm"%></span>
</div>

<% end %>

<div class="col-md-8 ml-auto mr-auto mt-5">
    <p>
        <%= Micro.Blog.Post.as_markdown(@post.body) %>
    </p>
</div>


<!-- Likes  -->
<!--
    <nav class="mt-5 clear-nav mb-2">
        <ul class="nav nav-tabs justify-content-center">
            <li class="nav-item">
                <a class="nav-link active post-nav" href="#">likes</a>
            </li>

        </ul>
    </nav>
-->
<hr>
<div class="row mt-3 align-items-center">
    <div class="col-md-2">
        <p class="m-auto" id="like-count"> </p>
    </div>
    <div class="col-md-1">

    <%= if @current_user do %>
        <button id="like-button" class="btn btn-sm btn-primary mt-auto"
            data-user-id="<%= @current_user.id %>">
            </button>

<!--
        <%= if Micro.Blog.get_like!(@post.id, @current_user.id) do %>
            <button id="like-remove-button" class="btn btn-sm btn-primary mt-auto"
             data-user-id="<%= @current_user.id %>"
             data-like-id="<%= Micro.Blog.get_like!(@post.id, @current_user.id).id %>">
                unlike
            </button>
        <% else %>
            <button id="like-add-button" class="btn btn-sm btn-primary mt-auto"
                    data-user-id="<%= @current_user.id %>">
                        like
            </button>
        <% end %>
-->
    <% end %>

    </div>
</div>



<div id="post-likes"
     data-path="<%= like_path(@conn, :index) %>"
     data-post_id="<%= @post.id %>">
</div>



<script id="likes-template" type="text/x-handlebars-template">
    <div class="mt-2">

    {{#each data}}
        <div class="row mt-3">
        <div class="col-md-8">
        <a class="card-tag" href="#">
            <span class="font-weight-bold h4">
                {{user_name}}
            </span>
            @{{user_handle}}
        </a>
        </div>
        </div>
    {{else}}
        <p> be the first to like this post </p>
    {{/each}}

    </div>
</script>