lib/micro_web/router.ex
defmodule MicroWeb.Router do
  use MicroWeb, :router
  import MicroWeb.Plugs

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_user
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_user
  end


  scope "/", MicroWeb do
    pipe_through :browser # Use the default browser stack
    get "/", PageController, :index

    # associate posts with users
    resources "/users", UserController do
      resources "/posts", PostController
    end

    post "/relationships", RelationshipController, :follow
    delete "/relationships", RelationshipController, :unfollow
    resources "/relationships", RelationshipController

    post "/sessions", SessionController, :login
    delete "/sessions", SessionController, :logout
  end

  scope "/api/v1", MicroWeb do
    pipe_through :api
    #get "/likes", LikeController, :show
    delete "/likes", LikeController, :delete
    post "/likes", LikeController, :create
    resources "/likes", LikeController, except: [:edit, :delete]

  end


  # Other scopes may use custom stacks.
  # scope "/api", MicroWeb do
  #   pipe_through :api
  # end
end

lib/micro_web/views/layout_view.ex
defmodule MicroWeb.LayoutView do
  use MicroWeb, :view
end

lib/micro_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Micro!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
   <!-- <link rel="stylesheet" href="<%= static_path(@conn, "/css/navbar.css") %>"> -->
  </head>

  <body>
  <%= if @current_user do %>
    <%= tag :meta, name: "user_channel", content: @conn.assigns[:current_user].id %>
  <% end %>

  <!-- Navbar -->
  <nav id="main-nav" class="navbar navbar-expand-lg navbar-dark navbar-expand-md">
        <%= if @current_user do %>
            <a class="navbar-brand" href="<%= relationship_path(@conn, :index, view: "home", user: @current_user) %>">
                <img src="<%= static_path(@conn, "/images/mu.png") %>" width="40" height="40" alt="logo">
                <strong>micro</strong>
            </a>

        <% else %>
            <a class="navbar-brand" href="<%= page_path(@conn, :index) %>">
                <img src="<%= static_path(@conn, "/images/mu.png") %>" width="40" height="40" alt="logo">
                <strong>micro</strong>
            </a>

        <% end %>

      <button class="navbar-toggler" type="button" data-toggle="collapse"
              data-target="#main-navbar"
               aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>

        <div class="collapse navbar-collapse" id="main-navbar">

          <ul class="navbar-nav justify-content-end">

              <li class="nav-item ">
              <%= if @current_user do %>
                   <a class="nav-link" href="<%= relationship_path(@conn, :index, view: "explore_users", user: @current_user) %>"><strong>explore</strong></a>
              <% end %>
              </li>

              <%= if @current_user do %>
                <li class="nav-item">
                    <a class="nav-link" href="<%= user_post_path(@conn, :new, @current_user) %>"><strong>post</strong></a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="<%= user_path(@conn, :show, @current_user) %>"><strong><%= @current_user.handle %></strong></a>
                </li>
                <li class="nav-item">
                    <!-- <a class="nav-link" href="<%= session_path(@conn, :logout, method: :delete) %>"><strong>sign out</strong></a> -->
                        <%= link("sign out", to: session_path(@conn, :logout), method: :delete, class: "nav-link") %>
                </li>
              <% else %>
                <li class="nav-item">
                    <a class="nav-link nav-text" href="<%= user_path(@conn, :new)  %>"><strong>sign up</strong></a>
                </li>
              <% end %>
          </ul>
        </div>
      </div>
  </nav>


    <div class="container mt-5 mb-5">
      <header class="header">
      </header>

      <%= if get_flash(@conn, :info) do %>
        <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <% end %>
      <%= if get_flash(@conn, :error) do %>
        <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <% end %>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>